name = "my-ai-image"
pages_build_output_dir = "public"
compatibility_date = "2024-11-10"

[ai]
binding = "AI"

[env.production.ai]
binding = "AI"

[env.production.vars]
ALLOWED_ORIGIN = "https://my-ai-image.pages.dev"